### ISSUE TITLE
根据现有的代码 构建了一个 alpine edge 的镜像版本 需要的自取

### ISSUE THREAD

**Issue by 502647092** [Coding/WebIDE#347]
- 拉取镜像
```sh
docker run -d \
  --name webide \
  -p 8080:8080 \
  -v /home/app/webide:/root/.coding-ide \
  -v /home/app/maven/repo:/root/.m2/repository \
  --restart=always \
  miaowoo/webide
```
- DockerCompose
```yml
version: '3'
services:
  webide:
    image: miaowoo/webide
    ports:
      - 8080:8080
    volumes:
      - /home/app/webide:/root/.coding-ide
      - /home/app/maven/repo:/root/.m2/repository
```
- 镜像[Dockerfile](https://github.com/502647092/Dockerfile/tree/master/webide)
- 修改说明
  - 更新基础镜像到最新的 `alpine:edge`
  - 更新 `OpenJDK` 到 `8u191`
  - 调整了时区为 `Asia/Shanghai`
- 当前镜像版本
  - `latest` 默认版本
  - `go` Golang 开发版本
